name: 'inplace-envsubst-action'
description: inplace envsubst of multiple files
author: 'Jakub Travnik'
branding:
  icon: 'layers'
  color: 'black'
inputs:
  files:
    description: 'Files to run substitutions on.'
    required: true
  variables:
    description: 'Variables that you want to replace. All encountered if not defined.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
